fix: get previous and check restart count
jenkins-x-plugins/jx-preview pull request #435
Opened 2023-07-26 15:14 UTC by tomhobson

2023-07-26 15:15 UTC, tomhobson commented
/cc @msvticket @skiSocks

2023-07-27 11:39 UTC, tomhobson commented
@msvticket  ready for review!

2023-07-27 13:10 UTC, msvticket requested changes

2023-07-27 15:31 UTC, tomhobson commented on pkg/cmd/create/create.go
> +		logs := o.KubeClient.CoreV1().Pods(previewNamespace).GetLogs(pod.Name, &corev1.PodLogOptions{Previous: true, Container: highestRestartContainer})
Yep good point!

2023-07-28 11:33 UTC, msvticket approved these changes

2023-07-28 11:33 UTC, merged